In [26]:
# module import
import pandas as pd
import numpy as np

In [47]:
combat = pd.read_csv('train_combat.csv')

In [48]:
combat.tail()

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
696572,10,99111,365153,ay,4,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0
696573,10,99111,18888,bb,4,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0
696574,10,56949,40959,bd,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0
696575,10,56949,383233,az,1,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0
696576,10,56949,295229,ay,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
# make new column
combat["wk"] = 0

In [50]:
# month classification by week
def wk_classification(df):
    df.loc[df['day'] <= 7, ['wk']] = 1
    df.loc[(df['day'] > 7) & (df['day'] <= 14), ['wk']] = 2
    df.loc[(df['day'] > 14) & (df['day'] <= 21), ['wk']] = 3
    df.loc[df['day'] >  21, ['wk']] = 4
    return

wk_classification(combat)

In [51]:
combat.head()

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent,wk
0,1,58743,133491,aa,3,16,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,1
1,1,58743,354243,aa,1,5,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,1
2,1,110631,181339,aj,2,17,0.320921,6.548676,0.0,0.0,0.0,0.0,2.060704,1
3,1,87697,253151,ak,1,3,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,1
4,1,87697,295097,ak,1,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,1

In [52]:
# set index for groupby
combat.set_index(combat["acc_id"], inplace = True)

In [53]:
combat.columns[:6]

Index(['day', 'acc_id', 'char_id', 'server', 'class', 'level'], dtype='object')

In [54]:
# delete column to same index
combat = combat.drop(combat.columns[:6], axis=1)

In [55]:
# confirm indexing
combat.sort_index(ascending = True).head(10)

,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent,wk
acc_id,,,,,,,,
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2

In [56]:
combat.columns

Index(['pledge_cnt', 'random_attacker_cnt', 'random_defender_cnt', 'temp_cnt',
       'same_pledge_cnt', 'etc_cnt', 'num_opponent', 'wk'],
      dtype='object')

In [57]:
# groupby 'acc_id', "wk" and sum of other columns
t_group = combat.groupby(['acc_id', "wk"], sort = ['acc_id'])[combat.columns[:]].agg('sum')
t_group.head()

           pledge_cnt  random_attacker_cnt  random_defender_cnt  temp_cnt  \
acc_id wk
7      2          0.0                  0.0             0.000000  0.000000
       3          0.0                  0.0             0.000000  0.000000
       4          0.0                  0.0             0.000000  1.918911
15     1          0.0                  0.0             9.464516  0.000000
       2          0.0                  0.0             1.183064  0.000000

           same_pledge_cnt   etc_cnt  num_opponent  wk
acc_id wk
7      2               0.0  0.000000      0.000000   6
       3               0.0  0.000000      0.000000   9
       4               0.0  0.000000      0.294386  24
15     1               0.0  0.000000      0.196258  21
       2               0.0  1.126115      0.392515  42

In [58]:
act_wk1 = combat[combat["wk"]==1]
act_wk1.sort_index(ascending = True).head()

,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent,wk
acc_id,,,,,,,,
15,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,1
15,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,1
15,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,1
15,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,1
15,0.0,0.0,3.549193,0.0,0.0,0.0,0.098129,1

In [59]:
combat.columns

Index(['pledge_cnt', 'random_attacker_cnt', 'random_defender_cnt', 'temp_cnt',
       'same_pledge_cnt', 'etc_cnt', 'num_opponent', 'wk'],
      dtype='object')

In [60]:
ls = ['pledge_cnt', 'random_attacker_cnt', 'random_defender_cnt', 'temp_cnt',
       'same_pledge_cnt', 'etc_cnt', 'num_opponent', 'wk']

In [61]:
act_wk1 = combat[combat["wk"]==1].groupby("acc_id").sum()
act_wk1.rename(columns={'pledge_cnt':'pledge_cnt_1', 'random_attacker_cnt':'random_attacker_cnt_1', 'random_defender_cnt':'random_defender_cnt_1', 'temp_cnt':'temp_cnt_1', 'same_pledge_cnt':'same_pledge_cnt_1', 'etc_cnt':'etc_cnt_1', 'num_opponent':'num_opponent_1'},inplace=True)
act_wk2 = combat[combat["wk"]==2].groupby("acc_id").sum()
act_wk2.rename(columns={'pledge_cnt':'pledge_cnt_2', 'random_attacker_cnt':'random_attacker_cnt_2', 'random_defender_cnt':'random_defender_cnt_2', 'temp_cnt':'temp_cnt_2', 'same_pledge_cnt':'same_pledge_cnt_2', 'etc_cnt':'etc_cnt_2', 'num_opponent':'num_opponent_2'},inplace=True)
act_wk3 = combat[combat["wk"]==3].groupby("acc_id").sum()
act_wk3.rename(columns={'pledge_cnt':'pledge_cnt_3', 'random_attacker_cnt':'random_attacker_cnt_3', 'random_defender_cnt':'random_defender_cnt_3', 'temp_cnt':'temp_cnt_3', 'same_pledge_cnt':'same_pledge_cnt_3', 'etc_cnt':'etc_cnt_3', 'num_opponent':'num_opponent_3'},inplace=True)
act_wk4 = combat[combat["wk"]==4].groupby("acc_id").sum()
act_wk4.rename(columns={'pledge_cnt':'pledge_cnt_4', 'random_attacker_cnt':'random_attacker_cnt_4', 'random_defender_cnt':'random_defender_cnt_4', 'temp_cnt':'temp_cnt_4', 'same_pledge_cnt':'same_pledge_cnt_4', 'etc_cnt':'etc_cnt_4', 'num_opponent':'num_opponent_4'},inplace=True)
print(act_wk1)

        pledge_cnt_1  random_attacker_cnt_1  random_defender_cnt_1  \
acc_id
15          0.000000               0.000000               9.464516
19          0.000000               0.000000               1.183064
22         14.184718               0.000000               1.183064
28          0.000000               0.000000               0.000000
39          3.273396               0.000000               0.000000
55          0.000000               0.000000               0.000000
56          0.000000               0.000000               0.000000
58          0.000000               0.000000               0.000000
70         15.468402               0.000000               8.281451
80          0.000000               0.000000               2.366129
82          0.000000               0.000000               2.366129
83          0.000000               0.000000               0.000000
87          0.000000               0.000000               0.000000
89          0.000000               0.000000               0.000000
104         0.000000               0.000000               0.000000
105         0.000000               0.000000               1.183064
107         0.256737               0.000000               0.000000
108         0.000000               0.000000               0.000000
109         8.536504               5.125051               2.366129
110         0.449290               8.257026               0.000000
114         2.310633              31.604479               0.000000
120         0.000000               0.000000               1.183064
134         0.000000               0.000000               0.000000
143         0.000000               0.000000               0.000000
144         0.000000               0.000000               0.000000
146         0.000000               0.000000               0.000000
153         0.000000               0.000000               0.000000
157         0.000000               0.000000               0.000000
159         0.000000               0.000000               0.000000
175         0.000000               0.000000               0.000000
...              ...                    ...                    ...
130254      0.000000               0.000000               0.000000
130274      0.000000               0.000000               1.183064
130276      0.000000               0.000000               5.915322
130284      0.000000               0.000000               0.000000
130288      0.000000               0.000000               2.366129
130298      0.000000               0.000000               0.000000
130302      0.449290               0.000000               0.000000
130306      3.145028              72.604883               0.000000
130321      5.198924               0.000000               2.366129
130329      0.000000               0.000000               0.000000
130331     54.941712              16.798777               0.000000
130332      0.000000               0.000000               0.000000
130350      0.000000               0.000000               0.000000
130352      0.000000               0.000000               0.000000
130353      0.000000               0.000000               9.464516
130369      0.000000               0.000000               0.000000
130377      0.000000               6.263951               0.000000
130388      0.000000               0.000000               0.000000
130399      0.000000               0.000000               0.000000
130418      0.000000               0.000000               0.000000
130423      0.000000               0.000000               0.000000
130424      0.000000               0.000000               0.000000
130426      0.000000              18.791852               2.366129
130436      0.000000               0.000000               1.183064
130441      0.000000               0.000000               0.000000
130448      0.000000               0.000000               1.183064
130450      0.000000               0.000000               0.000000
130454      0.000000               0.000000               4.732258
130465      0.000000               0.000000               0.000000
130466     27.535040               0.000000               0.000000

        temp_cnt_1  same_pledge_cnt_1  etc_cnt_1  num_opponent_1  wk
acc_id
15        0.000000           0.000000   0.000000        0.196258  21
19        1.439183           0.000000   0.000000        0.196258  10
22        0.000000          12.398273   2.815288       15.209957  10
28        0.000000           0.000000   0.000000        0.000000   7
39        0.959456           0.000000   0.112612        5.004566  13
55        0.479728           0.000000   0.000000        0.098129   2
56        0.000000           0.000000   0.000000        0.000000  21
58        0.000000           0.000000   0.000000        0.000000   7
70        2.878367           0.000000   3.153123       14.228669  12
80        0.000000           0.000000   0.000000        0.196258   7
82        0.000000           0.000000   0.225223        0.392515   7
83        0.000000           0.000000   0.000000        0.000000   6
87        0.000000           0.000000   0.112612        0.098129   5
89        0.479728           0.000000   0.225223        0.196258   7
104       1.439183           0.000000   0.112612        0.392515   7
105       0.000000           0.000000  20.382686        7.948429   9
107       0.479728           0.000000   0.112612        0.588773  19
108       0.000000           0.000000   0.000000        0.000000   7
109       0.000000           0.000000   1.126115       10.892292  10
110       1.918911           0.000000   2.252231        3.925150   7
114       3.837822           6.199136   4.166626        9.616618  19
120       0.000000           0.000000   0.000000        0.098129   7
134       0.000000           0.000000   0.000000        0.000000  21
143       0.959456           0.000000   0.000000        0.196258   7
144       0.000000           0.000000   0.000000        0.000000  21
146       0.000000           0.000000   0.000000        0.000000  21
153       0.000000           0.000000   0.000000        0.000000   9
157       0.479728           0.000000   0.000000        0.098129  17
159       0.000000           0.000000   0.000000        0.000000   1
175       2.878367           0.000000   0.112612        0.686901   7
...            ...                ...        ...             ...  ..
130254    0.000000           0.000000   0.000000        0.000000   7
130274    0.000000           0.000000   0.000000        0.098129   1
130276    3.837822           0.000000   0.225223        1.373803  21
130284    0.000000           0.000000   0.000000        0.000000   4
130288    0.000000           0.000000   1.013504        0.392515   7
130298    2.878367           0.000000   0.000000        0.098129   7
130302    0.000000           0.000000   0.000000        0.686901   7
130306    0.000000           0.000000   0.000000        8.635330   4
130321    3.837822           0.000000   2.364842        8.144687  22
130329    0.000000           0.000000   0.000000        0.000000   1
130331    0.000000           0.000000  43.468049       69.377029  14
130332    0.479728           0.000000   1.013504        0.981288   6
130350    0.000000           0.000000   0.000000        0.000000   7
130352    0.000000           0.000000   0.000000        0.000000   5
130353    0.479728           0.000000   1.463950        1.471931   7
130369    0.000000           0.000000   0.000000        0.000000   7
130377    0.000000           0.000000   0.225223        1.177545   8
130388    0.000000           0.000000   0.000000        0.000000   2
130399    0.000000           0.000000   0.000000        0.000000   7
130418    0.000000           0.000000   0.000000        0.000000   7
130423    0.000000           0.000000   0.000000        0.000000   7
130424    0.000000           0.000000   0.000000        0.000000  11
130426    1.439183           0.000000   7.657584        7.359657   7
130436    0.000000           0.000000   0.000000        0.098129   2
130441    0.000000           0.000000   0.000000        0.000000  21
130448    0.000000           0.000000   0.112612        0.196258   7
130450    0.000000           0.000000   0.000000        0.000000   6
130454    0.000000           0.000000   0.450446        0.588773  14
130465    0.479728           0.000000   0.000000        0.098129   7
130466    0.959456           0.000000   2.927900       24.924704   8

[16632 rows x 8 columns]

In [62]:
act_wk1.reset_index(inplace=True)
act_wk2.reset_index(inplace=True)
act_wk3.reset_index(inplace=True)
act_wk4.reset_index(inplace=True)

In [63]:
del act_wk1["wk"]
del act_wk2["wk"]
del act_wk3["wk"]
del act_wk4["wk"]

In [64]:
act_mer1 = pd.merge(act_wk1, act_wk2, how='outer', on = "acc_id")
act_mer1.head(10)

,acc_id,pledge_cnt_1,random_attacker_cnt_1,random_defender_cnt_1,temp_cnt_1,same_pledge_cnt_1,etc_cnt_1,num_opponent_1,pledge_cnt_2,random_attacker_cnt_2,random_defender_cnt_2,temp_cnt_2,same_pledge_cnt_2,etc_cnt_2,num_opponent_2
0,15,0.000000,0.0,9.464516,0.000000,0.000000,0.000000,0.196258,0.000000,0.000000,1.183064,0.000000,0.000000,1.126115,0.392515
1,19,0.000000,0.0,1.183064,1.439183,0.000000,0.000000,0.196258,0.000000,3.131975,3.549193,0.000000,0.000000,0.112612,1.373803
2,22,14.184718,0.0,1.183064,0.000000,12.398273,2.815288,15.209957,17.779035,0.000000,1.183064,1.439183,37.194818,2.252231,18.448206
3,28,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,39,3.273396,0.0,0.000000,0.959456,0.000000,0.112612,5.004566,1.155316,0.000000,0.000000,0.959456,6.199136,0.563058,2.256961
5,55,0.000000,0.0,0.000000,0.479728,0.000000,0.000000,0.098129,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,56,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,58,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,70,15.468402,0.0,8.281451,2.878367,0.000000,3.153123,14.228669,3.401765,0.000000,2.366129,0.479728,0.000000,9.909814,9.027845
9,80,0.000000,0.0,2.366129,0.000000,0.000000,0.000000,0.196258,0.000000,0.000000,1.183064,0.000000,0.000000,0.112612,0.196258

In [65]:
act_mer2 = pd.merge(act_wk3, act_wk4, how='outer', on = "acc_id")
act_mer2.head(10)

,acc_id,pledge_cnt_3,random_attacker_cnt_3,random_defender_cnt_3,temp_cnt_3,same_pledge_cnt_3,etc_cnt_3,num_opponent_3,pledge_cnt_4,random_attacker_cnt_4,random_defender_cnt_4,temp_cnt_4,same_pledge_cnt_4,etc_cnt_4,num_opponent_4
0,7,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.918911,0.0,0.000000,0.294386
1,15,0.000000,0.0,11.830645,0.000000,0.000000,0.788281,0.883159,0.000000,0.0,16.562903,0.000000,0.0,0.112612,0.785030
2,16,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
3,18,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
4,19,0.000000,0.0,4.732258,0.000000,0.000000,2.590065,2.453219,0.000000,0.0,0.000000,0.479728,0.0,0.112612,0.196258
5,22,19.832931,0.0,0.000000,0.959456,12.398273,3.265734,25.120961,3.401765,0.0,1.183064,0.000000,0.0,13.738606,13.247382
6,28,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
7,39,0.000000,0.0,0.000000,0.000000,6.199136,0.000000,0.098129,0.000000,0.0,0.000000,0.000000,0.0,0.225223,0.098129
8,55,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
9,56,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000

In [66]:
act_mer = pd.merge(act_mer1, act_mer2, how = "outer", on = "acc_id").fillna(0)
act_mer

,acc_id,pledge_cnt_1,random_attacker_cnt_1,random_defender_cnt_1,temp_cnt_1,same_pledge_cnt_1,etc_cnt_1,num_opponent_1,pledge_cnt_2,random_attacker_cnt_2,...,same_pledge_cnt_3,etc_cnt_3,num_opponent_3,pledge_cnt_4,random_attacker_cnt_4,random_defender_cnt_4,temp_cnt_4,same_pledge_cnt_4,etc_cnt_4,num_opponent_4
0,15,0.000000,0.000000,9.464516,0.000000,0.000000,0.000000,0.196258,0.000000,0.000000,...,0.000000,0.788281,0.883159,0.000000,0.000000,16.562903,0.000000,0.000000,0.112612,0.785030
1,19,0.000000,0.000000,1.183064,1.439183,0.000000,0.000000,0.196258,0.000000,3.131975,...,0.000000,2.590065,2.453219,0.000000,0.000000,0.000000,0.479728,0.000000,0.112612,0.196258
2,22,14.184718,0.000000,1.183064,0.000000,12.398273,2.815288,15.209957,17.779035,0.000000,...,12.398273,3.265734,25.120961,3.401765,0.000000,1.183064,0.000000,0.000000,13.738606,13.247382
3,28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,39,3.273396,0.000000,0.000000,0.959456,0.000000,0.112612,5.004566,1.155316,0.000000,...,6.199136,0.000000,0.098129,0.000000,0.000000,0.000000,0.000000,0.000000,0.225223,0.098129
5,55,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,56,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,58,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,70,15.468402,0.000000,8.281451,2.878367,0.000000,3.153123,14.228669,3.401765,0.000000,...,0.000000,9.909814,7.948429,0.000000,0.000000,0.000000,0.000000,0.000000,17.342175,7.457785
9,80,0.000000,0.000000,2.366129,0.000000,0.000000,0.000000,0.196258,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.366129,0.479728,0.000000,0.000000,0.196258
10,82,0.000000,0.000000,2.366129,0.000000,0.000000,0.225223,0.392515,0.000000,0.000000,...,0.000000,0.112612,0.294386,0.000000,0.000000,0.000000,0.000000,0.000000,1.238727,0.588773
11,83,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,87,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129
13,89,0.000000,0.000000,0.000000,0.479728,0.000000,0.225223,0.196258,0.000000,0.000000,...,0.000000,0.112612,0.098129,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,104,0.000000,0.000000,0.000000,1.439183,0.000000,0.112612,0.392515,0.000000,0.000000,...,0.000000,0.112612,0.294386,0.000000,0.000000,1.183064,0.959456,0.000000,0.337835,0.392515
15,105,0.000000,0.000000,1.183064,0.000000,0.000000,20.382686,7.948429,0.000000,0.000000,...,0.000000,17.680010,7.359657,0.385105,0.000000,2.366129,0.000000,0.000000,13.062937,7.163399
16,107,0.256737,0.000000,0.000000,0.479728,0.000000,0.112612,0.588773,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.320921,0.000000,1.183064,0.479728,0.000000,0.112612,0.686901
17,108,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,109,8.536504,5.125051,2.366129,0.000000,0.000000,1.126115,10.892292,9.884373,0.000000,...,0.000000,3.828792,8.929717,2.952475,0.000000,1.183064,0.479728,0.000000,2.815288,4.219536
19,110,0.449290,8.257026,0.000000,1.918911,0.000000,2.252231,3.925150,0.000000,0.000000,...,0.000000,0.000000,0.196258,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129
20,114,2.310633,31.604479,0.000000,3.837822,6.199136,4.166626,9.616618,3.209212,23.916903,...,0.000000,13.175549,5.495210,1.155316,13.097352,0.000000,0.959456,0.000000,11.035930,5.593339
21,120,0.000000,0.000000,1.183064,0.000000,0.000000,0.000000,0.098129,0.000000,0.000000,...,0.000000,0.112612,0.490644,0.000000,0.000000,4.732258,0.000000,0.000000,0.225223,0.392515
22,134,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,143,0.000000,0.000000,0.000000,0.959456,0.000000,0.000000,0.196258,0.000000,0.000000,...,0.000000,0.000000,0.294386,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,144,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,146,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.337835,0.588773,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,153,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,157,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129,0.000000,0.000000,...,0.000000,0.225223,0.196258,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,159,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.479728,0.000000,1.351338,1.079416
29,175,0.000000,0.000000,0.000000,2.878367,0.000000,0.112612,0.686901,0.000000,0.000000,...,0.000000,0.000000,0.294386,0.000000,0.000000,0.000000,6.236461,0.000000,0.000000,1.275674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,128299,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19971,128374,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129
19972,128382,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19973,128440,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.225223,0.196258
19974,128446,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19975,128487,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19976,128604,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19977,128617,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,15.379838,0.000000,0.000000,0.000000,0.588773
19978,128733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19979,128865,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19980,128955,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.183064,1.439183,0.000000,2.364842,2.355090
19981,128997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19982,129011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.183064,0.000000,0.000000,0.000000,0.098129
19983,129038,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19984,129067,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,37.868429,0.000000,1.439183,6.199136,0.000000,12.167966
19985,129097,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.959456,0.000000,0.000000,0.196258
19986,129202,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19987,129238,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19988,129502,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.064184,0.000000,1.183064,0.000000,0.000000,2.139619,1.766318
19989,129559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.959456,6.199136,0.337835,0.588773
19990,129561,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19991,129586,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19992,129619,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19993,129724,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19994,129800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19995,129961,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19996,130005,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19997,130186,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19998,130313,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19999,130421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [70]:
activity_df = pd.read_csv('test_1_combat.csv')

In [71]:
activity_df.head()

,acc_id,pledge_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent,sum_pledge
0,7,0.0,1.918911,0.0,0.000000,0.294386,1.918911
1,15,0.0,0.000000,0.0,2.027007,2.256961,2.027007
2,16,0.0,0.000000,0.0,0.000000,0.000000,0.000000
3,18,0.0,0.000000,0.0,0.000000,0.000000,0.000000
4,19,0.0,1.918911,0.0,2.815288,4.219536,4.734199

In [69]:
ds = pd.merge(activity_df,act_mer,how = "outer")
ds.shape

(60000, 35)

In [25]:
ds.to_csv('08-22test1_combat.csv')